package me.anno.io.binary;

public class BinaryTypes {
    // for the values, a system would be nice
    public static final char OBJECT_NULL = 0;
    public static final char OBJECT_IMPL = 1;
    public static final char OBJECT_ARRAY = 2;
    public static final char OBJECT_ARRAY_2D = 3;
    public static final char OBJECTS_HOMOGENOUS_ARRAY = 4;
    public static final char OBJECT_LIST_UNKNOWN_LENGTH = 5;
    public static final char OBJECT_PTR = 6;
    public static final char BOOL = 7;
    public static final char BOOL_ARRAY = 8;
    public static final char BOOL_ARRAY_2D = 9;
    public static final char BYTE = 10;
    public static final char BYTE_ARRAY = 11;
    public static final char BYTE_ARRAY_2D = 12;
    public static final char CHAR = 13;
    public static final char CHAR_ARRAY = 14;
    public static final char CHAR_ARRAY_2D = 15;
    public static final char SHORT = 16;
    public static final char SHORT_ARRAY = 17;
    public static final char SHORT_ARRAY_2D = 18;
    public static final char INT = 19;
    public static final char INT_ARRAY = 20;
    public static final char INT_ARRAY_2D = 21;
    public static final char LONG = 22;
    public static final char LONG_ARRAY = 23;
    public static final char LONG_ARRAY_2D = 24;
    public static final char FLOAT = 25;
    public static final char FLOAT_ARRAY = 26;
    public static final char FLOAT_ARRAY_2D = 27;
    public static final char DOUBLE = 28;
    public static final char DOUBLE_ARRAY = 29;
    public static final char DOUBLE_ARRAY_2D = 30;
    public static final char STRING = 31;
    public static final char STRING_ARRAY = 32;
    public static final char STRING_ARRAY_2D = 33;
    public static final char VECTOR2F = 34;
    public static final char VECTOR3F = 35;
    public static final char VECTOR4F = 36;
    public static final char VECTOR2D = 37;
    public static final char VECTOR3D = 38;
    public static final char VECTOR4D = 39;
    public static final char QUATERNION32 = 40;
    public static final char QUATERNION64 = 41;
    public static final char VECTOR2F_ARRAY = 42;
    public static final char VECTOR3F_ARRAY = 43;
    public static final char VECTOR4F_ARRAY = 44;
    public static final char VECTOR2D_ARRAY = 45;
    public static final char VECTOR3D_ARRAY = 46;
    public static final char VECTOR4D_ARRAY = 47;
    public static final char QUATERNION32_ARRAY = 48;
    public static final char QUATERNION64_ARRAY = 49;
    public static final char VECTOR2I = 50;
    public static final char VECTOR3I = 51;
    public static final char VECTOR4I = 52;
    public static final char FILE = 53;
    public static final char FILE_ARRAY = 54;
    // todo matrix types...
}
